# File: .docker/nginx.conf
server {
    listen 8000;
    root /app/public;
    index index.php index.html;

    # Set server name (optional, but good practice)
    server_name _;

    # Standard Laravel routing logic
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP scripts to PHP-FPM
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000; # This is the default port for PHP-FPM
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Hide dot files (like .env)
    location ~ /\. {
        deny all;
    }
}